/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itec103_design;
import itec103_design.Connection.DBConnection;
import itec103_design.Helpers.HelperClass;
import itec103_design.Model.Category;
import java.sql.Connection;
import itec103_design.Model.User;
import itec103_design.Model.UserManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Janice
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form JFrame4
     */
    Connection con = null;
    HelperClass hp = null;
    public Users() {
        initComponents();
        setUser();
        con = DBConnection.connect();
        hp = new HelperClass();
        getAllUsers("SELECT * FROM users ORDER BY user_id ASC");
        this.setLocationRelativeTo(null);
    }
    
    private void setUser(){
        User currentUser = UserManager.getCurrentUser();
        System.out.println("User: " + currentUser.getFirstname());
        user.setText(currentUser.getFirstname() + ' ' + currentUser.getLastname());
        String role = currentUser.getRole();
        int number = Integer.parseInt(role);
        if(number == 0) {
            purchased.setVisible(false);
        }
    }
    
    private void getAllUsers(String query){
            
            List<User> users = hp.getUsers(query);
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            TableColumnModel columnModel = userTable.getColumnModel();
            userTable.setRowHeight(30);
            columnModel.getColumn(0).setMinWidth(0);        
            columnModel.getColumn(0).setMaxWidth(0);
            columnModel.getColumn(1).setMinWidth(30);        
            columnModel.getColumn(1).setMaxWidth(30);
            int count = 0;
            model.setNumRows(0);
            for (User user : users) {
                count += 1;
                String role = (Integer.parseInt(user.getRole()) == 1) ? "Admin" : "Employee";
                model.addRow(new Object[]{user.getUserId(),count, user.getFirstname(), user.getLastname(), role, user.getCreatedAt()});
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        categories = new javax.swing.JButton();
        products = new javax.swing.JButton();
        purchased = new javax.swing.JButton();
        usersLink = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search_user = new javax.swing.JTextField();
        find_user = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(237, 121, 13));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itec103_design/hols_logo.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel1.setRequestFocusEnabled(false);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 190));

        logout.setBackground(new java.awt.Color(242, 242, 242));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.setBorderPainted(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setDisabledIcon(null);
        logout.setFocusPainted(false);
        logout.setFocusable(false);
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setIconTextGap(10);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 180, 40));

        dashboard.setBackground(new java.awt.Color(242, 242, 242));
        dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.setDisabledIcon(null);
        dashboard.setFocusPainted(false);
        dashboard.setFocusable(false);
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboard.setIconTextGap(10);
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 40));

        categories.setBackground(new java.awt.Color(242, 242, 242));
        categories.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        categories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/categories.png"))); // NOI18N
        categories.setText("Categories");
        categories.setAutoscrolls(true);
        categories.setBorderPainted(false);
        categories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categories.setDisabledIcon(null);
        categories.setFocusPainted(false);
        categories.setFocusable(false);
        categories.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categories.setIconTextGap(10);
        categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesActionPerformed(evt);
            }
        });
        jPanel2.add(categories, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 40));

        products.setBackground(new java.awt.Color(242, 242, 242));
        products.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products.png"))); // NOI18N
        products.setText("Products");
        products.setBorderPainted(false);
        products.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        products.setDisabledIcon(null);
        products.setFocusPainted(false);
        products.setFocusable(false);
        products.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        products.setIconTextGap(10);
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        jPanel2.add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, 40));

        purchased.setBackground(new java.awt.Color(242, 242, 242));
        purchased.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        purchased.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchased.png"))); // NOI18N
        purchased.setText("Orders");
        purchased.setBorderPainted(false);
        purchased.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purchased.setDisabledIcon(null);
        purchased.setFocusPainted(false);
        purchased.setFocusable(false);
        purchased.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        purchased.setIconTextGap(10);
        purchased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasedActionPerformed(evt);
            }
        });
        jPanel2.add(purchased, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 180, 40));

        usersLink.setBackground(new java.awt.Color(237, 121, 13));
        usersLink.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usersLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users.png"))); // NOI18N
        usersLink.setText("Users");
        usersLink.setBorderPainted(false);
        usersLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usersLink.setFocusPainted(false);
        usersLink.setFocusable(false);
        usersLink.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usersLink.setIconTextGap(10);
        usersLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersLinkActionPerformed(evt);
            }
        });
        jPanel2.add(usersLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 180, 40));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 547));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        user.setForeground(new java.awt.Color(237, 121, 13));
        user.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        user.setText("User");
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 130, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Users");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFocusable(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("User Lists");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Managing employee information and permission.");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("User Management");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        search_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        search_user.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        search_user.setToolTipText("");
        search_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_userMouseClicked(evt);
            }
        });
        search_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_userActionPerformed(evt);
            }
        });
        search_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_userKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_userKeyReleased(evt);
            }
        });
        jPanel4.add(search_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 250, 30));

        find_user.setBackground(new java.awt.Color(237, 121, 13));
        find_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        find_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_userActionPerformed(evt);
            }
        });
        jPanel4.add(find_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 70, 30));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "#", "First Name", "Last Name", "Role", "Date Added"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        userTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userTableKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(userTable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 740, 300));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Search User");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 110, -1));

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        int input = JOptionPane.showConfirmDialog(null, 
                "Are you sure do you want to logut?", "Select an Option...",JOptionPane.YES_NO_OPTION);
	// 0=yes, 1=no, 2=cancel
        if(input == 0) {
               
            boolean d = hp.changeFrame(new Login());
            if(d)this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed


    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
        
        boolean d = hp.changeFrame(new Dash());
        if(d)this.dispose();
    }//GEN-LAST:event_dashboardActionPerformed

    private void categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesActionPerformed
        try {
          
            boolean d = hp.changeFrame(new Categories());
            if(d)this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_categoriesActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
       
        boolean d = hp.changeFrame(new Products());
        if(d)this.dispose();
    }//GEN-LAST:event_productsActionPerformed

    private void purchasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasedActionPerformed
         
        boolean d = hp.changeFrame(new Orders());
        if(d)this.dispose();
    }//GEN-LAST:event_purchasedActionPerformed

    private void usersLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersLinkActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_usersLinkActionPerformed

    private void search_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_userMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_search_userMouseClicked

    private void search_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_userActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_search_userActionPerformed

    private void search_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_userKeyPressed
    formValidationWithEnter(evt);        
    }//GEN-LAST:event_search_userKeyPressed

    private void search_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_userKeyReleased
        
    }//GEN-LAST:event_search_userKeyReleased
    
    private boolean matchedWordLike(String word, String searchWord) {
       boolean found = word.toLowerCase().contains(searchWord.toLowerCase());
       return found;
    }
    
    private void searchUser() {
        String srchValue = search_user.getText();
        String query = null;
        String role = null;
        boolean admin = matchedWordLike("Admin", srchValue);        
        boolean emp = matchedWordLike("Employee", srchValue);
        if(admin) role = "1";
        if(emp) role = "0";
        
        if(!search_user.getText().isBlank()){
            query = "SELECT * FROM users where firstname LIKE '%"+srchValue+"%' OR lastname LIKE '%"+srchValue+"%' OR role LIKE '%"+role+"%' OR created_at LIKE '%"+srchValue+"%'";
            getAllUsers(query);
        } else {
            getAllUsers("SELECT * FROM users ORDER BY user_id ASC");
        }    
    }
    private void find_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_userActionPerformed
       
        searchUser();
        
    }//GEN-LAST:event_find_userActionPerformed

    private void userTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTableKeyPressed
        
    }//GEN-LAST:event_userTableKeyPressed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
//        String user = categorylist.getSelectedItem();
//        System.out.println("Double "+ category);
//
//        Statement st = con.createStatement();
//        String query = "UPDATE categories SET status='1' WHERE category_name = '"+category+"'";
//        st.execute(query);
//        getCategories();
    }//GEN-LAST:event_userTableMouseClicked
    
    public void formValidationWithEnter(java.awt.event.KeyEvent evt) {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            searchUser();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton categories;
    javax.swing.JButton dashboard;
    javax.swing.JButton find_user;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JButton logout;
    javax.swing.JButton products;
    javax.swing.JButton purchased;
    javax.swing.JTextField search_user;
    javax.swing.JLabel user;
    javax.swing.JTable userTable;
    javax.swing.JButton usersLink;
    // End of variables declaration//GEN-END:variables
}
